kubernetes/cray-console-node/Chart.yaml, kubernetes/cray-console-node/templates/hook-postupgrade.yaml, kubernetes/cray-console-node/values.yaml
Add `alpine.image` settings to values.yaml in order to enable customization.
Change default alpine reference from `artifactory.algol60.net/docker.io/alpine:latest` to `alpine:latest`. Chart defaults should reference upstream locations instead of registry mirrors.
Supplements [CASMCMS-7695](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7695). Required to resolve [CASM-2670](https://jira-pro.its.hpecorp.net:8443/browse/CASM-2670).
=> Refactor alpine image references

kubernetes/cray-console-node/templates/hook-postupgrade.yaml
The post-upgrade hook was setting a permission level that didn't work with the ssh key for mountain console connections.  The ssh key needs to be private to the current user or the ssh connection will fail.  This level of permission works for all files on the /var/log mount, so I just changed the hook to set this same permission on all log files.  They will all be read/write accessible for the user the container is started under.
* Resolves [CASMTRIAGE-2915](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-2915)
* Change will also be needed in `https://github.com/Cray-HPE/console-operator`
* `Hela`
The file permissions had manually been changed to '700' to make the ssh connections work.  I restored the permissions to '766' and verified the ssh connections were not working.  I …
=> Change file permissions so ssh key works.

Dockerfile
Build the console-node container with SP3 as the base image instead of SP2, to avoid a CVE. No other changes.
[CASM-2794](https://jira-pro.its.hpecorp.net:8443/browse/CASM-2794) / [CASMCMS-7787](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7787)  The new cray-console-node image also addresses this CVE
On mug I applied the new console-node and ran the barebones boot test. I was able to watch the compute node console using the new console-node pod with no problems.
I think this is low risk. Going from a base image of SP2 to SP3 should not affect how conman works.
- [N/A] Version number(s) incremented, if applicable
- [N/A] CHANGELOG.md updated
- [N/A] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable
=> CASMCMS-7786: Move to SLES15SP3 to avoid CVE

Dockerfile
Remove the 'polkit' package from the published image.  This package is installed as part of the 'vi' zypper install but is not required by any of the basic functions of the services.  Furthermore it frequently has CVE vulnerabilities that require patching.  In an effort to improve the long term security of this service, this package is being deliberately removed from the image.  As it is not required, it has no impact on the running of this service. 
* Resolves [CASMCMS-7793](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7793)
* Mug
I did a Helm install/upgrade of the new image on Mug.  When the new version was up and running I confirmed the basic operations of the service (interactive console access and logging) was working correctly.  I then did a Helm rollback to restore the …
=> Remove polkit from image.

CHANGELOG.md, kubernetes/cray-console-node/values.yaml
To minimize the possibility that multiple console-node pods will be run on the same worker node, anti-affinity pod settings were added to the helm chart specification.  This will insure pods are scheduled on different workers (where able) and help the resiliency of the console services. 
* Resolves [CASMCMS-8055](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8055)
* `Drax`
I updated the deployment on Drax using a helm install.  When the new service was running, I deleted the pods multiple times and insured that they were never deployed on the same worker.  I then rolled back the install to the previous version and when pods were deleted they re-deployed on the same worker as other console-node pods were already running on.
- Were the install/upgrade-based validation checks/tests …
=> CASMCMS-8055 - add anti-affinity.

CHANGELOG.md, Dockerfile
The dev.cray.com network domain is being retired, so update to the new location of the servers.
* Resolves [CASMCMS-7830](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7830)
* `Drax`
Installed via helm on Drax with the other console services.  Did complete test with flushing cached data and made sure all new services came up and operated as expected, including connecting to live console sessions on compute nodes.  Rolled back to previous installed version when complete and re-tested.
- Were continuous integration tests run? If not, why? N - not applicable
- Was upgrade tested? If not, why? Y
- Was downgrade tested? If not, why? Y
- Were new tests (or test issues/Jiras) created for …
=> CASMCMS-7830 - migrate away from arti.dev.cray.com

CHANGELOG.md, Dockerfile
Got a little carried away cleaning up the dockerfile - put back in the code from the last PR that removes 'polkit' from the image.  It isn't needed and can expose security vulnerabilities.
Removed in: https://github.com/Cray-HPE/console-node/pull/48
* Resolves [CASMCMS-7830](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7830)
See previous PR.
See previous PR.
=> CASMCMS-7830 - put back dockerfile commands to remove polkit.

CHANGELOG.md, kubernetes/cray-console-node/values.yaml
The hsm v1 interface is being removed from the service, so we needed to switch to using the v2 interface.  The endpoints that we are using are identical in both versions so this was a minimal change.
* Resolves [CASMCMS-8016](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8016)
* `Mug`
I used helm to upgrade the existing deployments of console-operator and console-node, forced a complete regeneration of the console connections, and verified the information needed is being pulled correctly from the new hsm interface and the console connections were correctly established.  I then reverted to the original versions of the services and again forced a regeneration fo the connections and verified they worked correctly.
- Were the install/upgrade-based validation checks/tests run (goss …
=> CASMCMS-8016 - update hsm api to use v2.

src/console_node/nodes.go
In csm-1.2, hsm changed so that the 'node class' can be either 'Mountain', 'River', or 'Hill'.  The 'hill' types were not getting picked up by console services.  This set of changes looks for records containing 'Hill' and treats them correctly.
* Resolves [CASMCMS-8140](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8140)
* `Loki`
I installed the new version via helm and observed that Hill nodes were correctly picked up by console services and connections and logging were established.
- Was upgrade tested? If not, why? Y
- Was downgrade tested? If not, why? Y
- Were new tests (or test issues/Jiras) created for this change? Y
This …
=> CASMCMS-8140 - correctly handle Hill nodes.

CHANGELOG.md, kubernetes/cray-console-node/Chart.yaml, kubernetes/cray-console-node/values.yaml, update_versions.conf
After Ryan noticed that a CFS build of his was not using the expected version strings in the Chart artifact, we looked into it and discovered that this was because the build was taking the docker and chart version strings from the wrong source. Specifically, it was taking them from the .version file, which did not include the "beta" tag that he was expecting. It should have been getting the docker and chart version strings from .docker_version and .chart_version respectively.
For tagged builds on the master branch, there is no difference in the contents of those files. But if doing builds in release branches, for example, the difference is apparent. 
I corrected the issue in the CFS repo with this PR:
https://github.com/Cray-HPE/config-framework-service/pull/51
I then reviewed all of the …
=> CASMCMS-8252: Update Chart with correct version strings during builds; enable unstable artifact builds

CHANGELOG.md, Dockerfile
Add 'nobody' user. For an unknown reason, the SLES15SP3 image we get from the algol60 artifactory does not have the 'nobody' user present in it. This adds it.
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves CASMCMS-8353
_List the environments in which these changes were tested._
* 'Shandy'
I built the image and uploaded it to Shandy. I relaunched the cray-console-node statefulset using this new Docker image. I exec'd into one statefulset and saw that the 'nobody' user existed and that I could interactively connect to a node.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why? No.
- Was upgrade tested? If not, why? …
=> Add nobody user

CHANGELOG.md, kubernetes/cray-console-node/templates/hook-postupgrade.yaml
This hook is working on a PVC that is created by the console-operator helm chart. If this chart is deployed before the operator chart, the hook will fail since that PVC isn't created yet. Do not run the hook on an install, just an upgrade since the upgrade case should have the operator already deployed hence the PVC will exist.
I also added a condition to delete the hook job when complete no matter what. The presence of the hook job can keep a handle on the PVC and not allow it to be removed when uninstalling the chart.
* Resolves [CASMINST-5878](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5878)
* `Fanta`
* Local development environment
* Virtual Shasta
I did helm install/uninstall/upgrade operations in every order I could think of, including with the cray-console-operator chart …
=> CASMINST-5878 - remove post-install hook.

CHANGELOG.md, src/console_node/logRotation.go
There was a new version of 'go' installed on the image for the build pipeline. The new 'gofmt' linter objected to a couple of the comments and forced us to change them to allow the linting step to complete happily so the build would complete.
* Resolves [CASMCMS-8423](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8423)
* `Surtur`
Installed the new version on surtur and verified the console services work correctly.
- Was upgrade tested? If not, why? Y 
- Was downgrade tested? If not, why? Y
- Were new tests (or test issues/Jiras) created for this change? N
Very low risk - just changing the format of comments.
=> CASMCMS-8423 - Linting changes for new version of gofmt.

CHANGELOG.md, src/console_node/conman.go, src/console_node/consoleNodeMain.go, src/console_node/monitor.go
Adds a new routine that regularly checks for new mountain/river credentials so that conman can be restarted to pick up the changes.
* Resolves CASMCMS-7169
* Surtur
- Tested no changes, and simulated changes for both the river and mountain credentials
None
=> CASMCMS-7169: Add new thread to check for passwords/creds changes

CHANGELOG.md, Dockerfile, scripts/ssh-key-console, scripts/ssh-pwd-console, src/console_node/conman.go, src/console_node/consoleNodeMain.go, src/console_node/creds.go, src/console_node/data.go, src/console_node/health.go, src/console_node/httpUtils.go, src/console_node/logAggregation.go, src/console_node/logRotation.go, src/console_node/monitor.go, src/console_node/nodes.go, src/console_node/operator.go
Paradise nodes (Cray xd224) needs to connect to the consoles through ssh but with a username and password, which is a different way of connecting than to regular river, mountain, or hill nodes. The changes in this service mostly have to do with identifying and labeling nodes that are paradise hardware.
* Resolves [CASMCMS-8899](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8899)
* `Tyr`
The new services were installed via helm and I manually tested that the existing mountain, hill, river, and paradise nodes all are identified correctly and the console services can connect with them.
- Was upgrade tested? If not, why? Y
- Was …
=> CASMCMS-8899 - Support Paradise nodes for console logging.

CHANGELOG.md, Dockerfile
The base image sles15-sp4 is no longer supported. To resolve some CVE's we updated to use sles15-sp5.
* Resolves [CASMCMS-9056](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9056)
* Resolves [CASMPET-7114](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7114)
* `Mug`
* Local development environment
Installed the new image and verified all normal operations are still working as expected.
- Was upgrade tested? If not, why? N
- Was downgrade tested? If not, why? N
- Were new tests (or test issues/Jiras) created for this change? N
Low risk as there isn't much from the base image being used.
=> CASMCMS-9056 - update base image to sles15-sp5

CHANGELOG.md, Dockerfile
A customer has requested that the 'inotify-tools' package be added to the base image for some utilities they want to build for handling log file changes.
* Resolves [CASMCMS-8681](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8681)
* Change will also be needed in `v2.3.0 branch` for hotfix to csm-1.5.x systems.
* `drax`
I installed the updated package using helm to make sure that the utilities worked and the hotfix would work in a 1.5.2 context.
- Was upgrade tested? If not, why? Y
- Was downgrade tested? If not, why? Y
- Were new tests (or test issues/Jiras) created for this change? N
Low risk - just adding a utility package to the …
=> CASMCMS-8681 - add inotify-tools to the base image.

CHANGELOG.md, src/console_node/httpUtils.go
[CASMCMS-9214](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9214) was opened to evaluate all CMS services for potential memory leaks, specifically related to HTTP clients. CASMCMS-9217 was opened to perform this evaluation on `console-node`.
I noticed that unlike for POST requests, the corresponding GET helper function does not include a `defer` call to close the response body. This PR adds that.
=> CASMCMS-9217: Close response bodies for GET requests; ; drain and close response bodies on error path, if needed

CHANGELOG.md
Although this small of a change normally would not merit bumping the minor number, in this case we want to do it because we are not pulling this change into CSM 1.6.0, only into CSM 1.6.1. We want to leave room to pull in critical fixes to CSM 1.6.0 if necessary, without being forced to also pull this in. Hence, the minor number bump.
=> v2.6.0 for CSM 1.6.n (n>=1)

CHANGELOG.md, src/console_node/consoleNodeMain.go, src/console_node/data.go, src/console_node/monitor.go, src/console_node/nodes.go, src/console_node/operator.go
There was a problem where a worker node's console was not being monitored by anyone because it was getting assigned/unassigned to the console-node pod that was running on that worker and the other pod didn't have capacity to pick it up. The end result was it was getting picked up and dropped continually while forcing the conmand process to keep getting killed (resulting in incomplete logging of all the nodes in that pod).
The fix was to rework how node acquisition and rebalancing happens to be much more stable and aware of the current status of the services. This fix requires changes in all three console repos.
At the same time I added a change to watch the permissions on the log files. There were problems where something was setting the files to unwritable and losing logging.
* Resolves …
=> CASMTRIAGE-7594 - improve node acquisition and rebalance.

CHANGELOG.md, kubernetes/cray-console-node/templates/hook-postupgrade.yaml, src/console_node/monitor.go
Something has been changing the directory permissions as well as log file permissions. This looks at directories as well, and tweaks the checking logic.
* Resolves [CASMTRIAGE-7715](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7715)
* `Mug`
I installed the test image, then would manually change the file permissions of the log files and directories. Watching the pod log files and file/directory permissions I verified that they were set back to correctly giving read/write access.
There were a few times the node pod crashed when a file was unexpectedly read-only, but it would restart and the permissions were corrected and the restarted pod worked as expected. This should be acceptable.
- …
=> CASMTRIAGE-7715 - fix resetting log file permissions.
